---
title: "First Knit"
author: "Shaun Ikeuchi"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I am currently attending Lancaster High school. Math is easier to me compared to English. I prefer math due to the greater applicability towards technology. Numbers allows us to better understand the universe.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I use a windows computer, but I have a linux virtual machine. I would consider myself an 8 (in order to be a 10, I need to be the founding fathers of Microsoft which I am not) due to my decent knowledge in programming and windows/linux internals. My bandwith and latency is fine enough for me unless an assignment requires me to open 100 tabs.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I do have nicknames, however, I prefer not be called these nicknames in class and instead prefer to be called by my first name, Shaun.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
Due to this vaguely worded question, what I want to achieve in life is to visit 200 skyscrapers over 1,000 feet tall, achieve the power of invisibility, and to get deep into web3 technologies.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have been to Osaka, Japan. I have not been in the military, but if I had to choose a branch, it would be in the space form because warfare in space seems surreal and fun compared to being stuck on Earth.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I am taking Math 115, and I never knew that Math 115 only satisfies a general education requirement. I plan on getting 100% in attendance with a 99% confidence interval, so you can make an assumption on what grade I plan on getting. I plan on applying statistics to the the world we live in order to parse randomness from simple manipulation of numbers.
 






  




